site_name: Phoenix Suite Wiki
site_url: https://p-h-o-e-n-i-x-packforge.github.io/PhoenixSuite/wiki/
repo_name: PhoenixSuite
repo_url: https://github.com/P-H-O-E-N-I-X-PackForge/PhoenixSuite
edit_uri: blob/main/wiki/content/
docs_dir: content
site_dir: ../public/wiki

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: deep-purple
      accent: pink
      toggle:
        icon: material/flower
        name: Sakura (light) switch to Sakura (dark)
    - scheme: slate
      primary: deep-purple
      accent: pink
      toggle:
        icon: material/flower
        name: Sakura (dark) switch to Ember (light)
    - scheme: default
      primary: deep-purple
      accent: deep-orange
      toggle:
        icon: material/fire
        name: Ember (light) switch to Ember (dark)
    - scheme: slate
      primary: deep-purple
      accent: deep-orange
      toggle:
        icon: material/fire
        name: Ember (dark) switch to Void (light)
    - scheme: default
      primary: deep-purple
      accent: cyan
      toggle:
        icon: material/creation
        name: Void (light) switch to Void (dark)
    - scheme: slate
      primary: deep-purple
      accent: cyan
      toggle:
        icon: material/creation
        name: Void (dark) switch to Sakura (light)
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - navigation.top
    - toc.follow
    - content.code.annotate
    - content.action.view

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - md_in_html
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
